# Entry point for development sites.
# 1) Main domain
# 2) Subdomains (ordered by filename in subdomain/)
import /etc/caddy/sites/apps/development/domain.conf
import /etc/caddy/sites/apps/development/subdomain/*.conf
