# Entry point for production sites.
# 1) Main domain
# 2) Subdomains (ordered by filename in subdomain/)
import /etc/caddy/sites/apps/production/domain.conf
import /etc/caddy/sites/apps/production/subdomain/*.conf
