# Service subdomains (production)
# Reorder imports here to change service load order.
# import /etc/caddy/sites/services/conf/*.conf

import /etc/caddy/sites/services/conf/20-log.conf
import /etc/caddy/sites/services/conf/30-mail.conf
import /etc/caddy/sites/services/conf/40-webmail.conf